apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Pods
      resource:
        name: qps
        targetAverageValue: 100
