@startuml
You -> Mint: show my transactions
Mint --> You: I can't, I'll redirect you
You -> AuthorizationServerBoA: give mint access to my transactions
AuthorizationServerBoA --> You: give me your credentials
You -> AuthorizationServerBoA: credentials
rnote over AuthorizationServerBoA
  check credentials
endrnote
AuthorizationServerBoA --> You: OK, redirecting you to mint with an access token
You -> Mint: show transactions \ngiven my access token
Mint -> BankOfAmerica: here's the access token,\n give me data
rnote over BankOfAmerica
  check access token
endrnote
BankOfAmerica --> Mint: transactions
Mint --> You: transactions
@enduml