@startuml
rnote over AuthorizationServerBoA
  check credentials
endrnote
AuthorizationServerBoA --> You: you're good, I'm redirecting you back to the client with an access token
You -> Mint: I'm back with an access token from the authorization server
@enduml