@startuml
User -> Client:  get data
Client --> User: I can't, I'll redirect you
User -> AuthorizationServer: I want to give Client access to data
AuthorizationServer --> User: give me your credentials
User -> AuthorizationServer: credentials
rnote over AuthorizationServer
  check credentials
endrnote
AuthorizationServer -> User: OK, redirecting you to Client with an access token
User -> Client: get data with access token
Client -> ResourceOwner: get data with access token
rnote over ResourceOwner
  check access token
endrnote
ResourceOwner --> Client: data
Client --> User: data
@enduml