@startuml
You -> Mint: show me my data
Mint --> You: I can't, I'll redirect you
You -> AuthorizationServerBoA: I want to give mint access to my data
AuthorizationServerBoA --> You: give me your credentials
You -> AuthorizationServerBoA: credentials
rnote over AuthorizationServerBoA
  check credentials
endrnote
AuthorizationServerBoA --> You: you're good, I'm redirecting you back to the client with an access token
You -> Mint: I'm back with an access token from the authorization server
Mint -> BankOfAmerica: great, here's the access token for the user, give me data
rnote over BankOfAmerica
  check access token
endrnote
BankOfAmerica --> Mint: here you go
Mint --> You: here's your transactions by category
@enduml